# Generated by Django 4.2.5 on 2023-10-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jupiter_app', '0006_delete_login_alter_paciente_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
