# Generated by Django 4.2.5 on 2023-10-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jupiter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='paciente',
            name='celular',
            field=models.CharField(default='XX XXXX-XXXX', max_length=14),
        ),
        migrations.AddField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(default='Sem Complemento', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='XXX.XXX.XXX-XX', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
    ]
