# Generated by Django 4.2.5 on 2023-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jupiter_app', '0002_login_remove_paciente_telefone_paciente_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='cpf',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
