# Generated by Django 4.2.5 on 2023-10-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jupiter_app', '0003_remove_login_cpf_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, default='Sem Complemento', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
