# Generated by Django 4.2.5 on 2023-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jupiter_app', '0004_alter_paciente_celular_alter_paciente_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, default='Nada Consta', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cep',
            field=models.CharField(default='none', max_length=9),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='remedios',
            field=models.TextField(blank=True, default='Nada Consta', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(default='none', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='senha',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, default='Nada Consta', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(default='none', max_length=14),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(default='Sem Complemento', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='none', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default='none'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
