# Generated by Django 4.2.5 on 2023-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jupiter_app', '0010_alter_paciente_tipo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, default='Nada Consta', max_length=20, null=True),
        ),
    ]
